{
    'name': 'Odoo Inheritance',
    'version': '1.0.0',
    'category': 'Inhertance',
    'sequence': 1,
    'author': 'Yeasin Arafath',
    'summary': 'Odoo Inheritance',
    'description': """Odoo Inheritance""",
    'depends': ['sale'],
    'data': [],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}